server:
  port: 7070

spring:
  application:
    # 应用名称(集群内相同)
    name: product-service
  main:
    # 循环依赖限制
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/micro_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: password
  #  zipkin:
  #    base-url: http://192.168.126.64:9411/ # 服务端地址
  #    sender:
  #      type: web                      # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  #  sleuth:
  #    sampler:
  #      probability: 1.0               # 收集数据百分比，默认 0.1（10%）

  zipkin:
    base-url: http://192.168.126.64:9411/ # 服务端地址
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin # 队列名称
  rabbitmq:
    host: 192.168.126.64 # 服务器 IP
    port: 5672 # 服务器端口
    username: lizongzai # 用户名
    password: password # 密码
    virtual-host: / # 虚拟主机地址
    listener:
      direct:
        retry:
          enabled: true # 是否开启发布重试
          max-attempts: 5 # 最大重试次数
          initial-interval: 5000 # 重试间隔时间（单位毫秒）
      simple:
        retry:
          enabled: true # 是否开启消费者重试
          max-attempts: 5 # 最大重试次数
          initial-interval: 5000 # 重试间隔时间（单位毫秒）
  sleuth:
    sampler:
      probability: 1.0 # 收集数据百分比，默认 0.1（10%）

# 配置Eureka Server注册中心
eureka:
  instance:
    # 是否开启IP地址注册
    prefer-ip-address: true
    # 主机地址+端口号
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

# 自定义配置
name: product-service-prod
# 非对称加密
password: '{cipher}AQCHS7QE+qd1W2kNlTutLoMRc6AQp/aeThht2g+U7jVwHST8QdwqnPgyLYxrLu+v1OeMPyzHxHBpbEQ7tFpY+f1203JOi0Y8BVYXHKepB43GEeBqLwfsbmjw+fxS7iy9MGGfCwwBB91bHuW5CwK9LSB73Pp+1z2pgQ50LkptRzMDh+Gh0yejAZsEy1mgSmjAarX9BDBmE40nHZVTDY8pshvkSdSXcyCJbGMt0mbT4o3YczSaF54aBFBkSQkemEIICdTU7sq0mLPIPXxA/QAzThPoCVfqJ0yVB1VnQTKnuLymf6KiWZjKI2v7QOOFkLu7SXG7fPv/pxc3l84N7qu49qjfNW9ImDwFWRtmzfJ0ENtM8Kh9r28/KIKUuQ5YQbVjaCQ='
